config/routes.rb
Rails.application.routes.draw do
  resources :captains
  resources :players
  resources :matches
  
  root 'players#index'

end

app/models/captain.rb
class Captain < ActiveRecord::Base
    belongs_to :player
end

app/models/match.rb
class Match < ActiveRecord::Base
    has_many :players
end

app/models/player.rb
class Player < ActiveRecord::Base
    belongs_to :match
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/captains_controller.rb
class CaptainsController < ApplicationController
  before_action :set_captain, only: [:show, :edit, :update, :destroy]

  # GET /captains
  # GET /captains.json
  def index
    @captains = Captain.all
  end

  # GET /captains/1
  # GET /captains/1.json
  def show
  end

  # GET /captains/new
  def new
    @captain = Captain.new
  end

  # GET /captains/1/edit
  def edit
  end

  # POST /captains
  # POST /captains.json
  def create
    @captain = Captain.new(captain_params)

    respond_to do |format|
      if @captain.save
        format.html { redirect_to @captain, notice: 'Captain was successfully created.' }
        format.json { render :show, status: :created, location: @captain }
      else
        format.html { render :new }
        format.json { render json: @captain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /captains/1
  # PATCH/PUT /captains/1.json
  def update
    respond_to do |format|
      if @captain.update(captain_params)
        format.html { redirect_to @captain, notice: 'Captain was successfully updated.' }
        format.json { render :show, status: :ok, location: @captain }
      else
        format.html { render :edit }
        format.json { render json: @captain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /captains/1
  # DELETE /captains/1.json
  def destroy
    @captain.destroy
    respond_to do |format|
      format.html { redirect_to captains_url, notice: 'Captain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_captain
      @captain = Captain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def captain_params
      params.require(:captain).permit(:captainTeam, :captainID)
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:matchID, :time, :team, :against, :competition, :scoreFor, :scoreAgainst, :playerID1, :playerID2, :playerID3, :playerID4, :playerID5, :playerID6, :playerID7, :playerID8, :playerID9, :playerID10, :playerID11, :playerID12, :playerID13, :playerID14, :playerID15, :playerID16)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:playerID, :name, :team, :email, :mobile, :availabilityNotes, :unavailableFrom, :unavailableUntil)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/captains_helper.rb
module CaptainsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/captains/_form.html.erb
<%= form_for(@captain) do |f| %>
  <% if @captain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@captain.errors.count, "error") %> prohibited this captain from being saved:</h2>

      <ul>
      <% @captain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :captainTeam %><br>
    <%= f.number_field :captainTeam %>
  </div>
  <div class="field">
    <%= f.label :captainID %><br>
    <%= f.number_field :captainID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/captains/edit.html.erb
<h1>Editing Captain</h1>

<%= render 'form' %>

<%= link_to 'Show', @captain %> |
<%= link_to 'Back', captains_path %>

app/views/captains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Captains</h1>
<h2>
  <a href="https://practice-database-simonina.c9users.io/players">Players</a>
</h2>
<h2>
  <a href="https://practice-database-simonina.c9users.io/matches">Matches</a>
</h2>

<table>
  <thead>
    <tr>
      <th>Captainteam</th>
      <th>Captainid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @captains.each do |captain| %>
      <tr>
        <td><%= captain.captainTeam %></td>
        <td><%= captain.captainID %></td>
        <td><%= link_to 'Show', captain %></td>
        <td><%= link_to 'Edit', edit_captain_path(captain) %></td>
        <td><%= link_to 'Destroy', captain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Captain', new_captain_path %>

app/views/captains/new.html.erb
<h1>New Captain</h1>

<%= render 'form' %>

<%= link_to 'Back', captains_path %>

app/views/captains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Captainteam:</strong>
  <%= @captain.captainTeam %>
</p>

<p>
  <strong>Captainid:</strong>
  <%= @captain.captainID %>
</p>

<%= link_to 'Edit', edit_captain_path(@captain) %> |
<%= link_to 'Back', captains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matchID %><br>
    <%= f.number_field :matchID %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :team %><br>
    <%= f.number_field :team %>
  </div>
  <div class="field">
    <%= f.label :against %><br>
    <%= f.text_field :against %>
  </div>
  <div class="field">
    <%= f.label :competition %><br>
    <%= f.text_field :competition %>
  </div>
  <div class="field">
    <%= f.label :scoreFor %><br>
    <%= f.number_field :scoreFor %>
  </div>
  <div class="field">
    <%= f.label :scoreAgainst %><br>
    <%= f.number_field :scoreAgainst %>
  </div>
  <div class="field">
    <%= f.label :playerID1 %><br>
    <%= f.number_field :playerID1 %>
  </div>
  <div class="field">
    <%= f.label :playerID2 %><br>
    <%= f.number_field :playerID2 %>
  </div>
  <div class="field">
    <%= f.label :playerID3 %><br>
    <%= f.number_field :playerID3 %>
  </div>
  <div class="field">
    <%= f.label :playerID4 %><br>
    <%= f.number_field :playerID4 %>
  </div>
  <div class="field">
    <%= f.label :playerID5 %><br>
    <%= f.number_field :playerID5 %>
  </div>
  <div class="field">
    <%= f.label :playerID6 %><br>
    <%= f.number_field :playerID6 %>
  </div>
  <div class="field">
    <%= f.label :playerID7 %><br>
    <%= f.number_field :playerID7 %>
  </div>
  <div class="field">
    <%= f.label :playerID8 %><br>
    <%= f.number_field :playerID8 %>
  </div>
  <div class="field">
    <%= f.label :playerID9 %><br>
    <%= f.number_field :playerID9 %>
  </div>
  <div class="field">
    <%= f.label :playerID10 %><br>
    <%= f.number_field :playerID10 %>
  </div>
  <div class="field">
    <%= f.label :playerID11 %><br>
    <%= f.number_field :playerID11 %>
  </div>
  <div class="field">
    <%= f.label :playerID12 %><br>
    <%= f.number_field :playerID12 %>
  </div>
  <div class="field">
    <%= f.label :playerID13 %><br>
    <%= f.number_field :playerID13 %>
  </div>
  <div class="field">
    <%= f.label :playerID14 %><br>
    <%= f.number_field :playerID14 %>
  </div>
  <div class="field">
    <%= f.label :playerID15 %><br>
    <%= f.number_field :playerID15 %>
  </div>
  <div class="field">
    <%= f.label :playerID16 %><br>
    <%= f.number_field :playerID16 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Matches</h1>
<h2>
  <a href="https://practice-database-simonina.c9users.io/players">Players</a>
</h2>
<h2>
  <a href="https://practice-database-simonina.c9users.io/captains">Captains</a>
</h2>

<table>
  <thead>
    <tr>
      <th>Matchid</th>
      <th>Time</th>
      <th>Team</th>
      <th>Against</th>
      <th>Competition</th>
      <th>Scorefor</th>
      <th>Scoreagainst</th>
      <th>Playerid1</th>
      <th>Playerid2</th>
      <th>Playerid3</th>
      <th>Playerid4</th>
      <th>Playerid5</th>
      <th>Playerid6</th>
      <th>Playerid7</th>
      <th>Playerid8</th>
      <th>Playerid9</th>
      <th>Playerid10</th>
      <th>Playerid11</th>
      <th>Playerid12</th>
      <th>Playerid13</th>
      <th>Playerid14</th>
      <th>Playerid15</th>
      <th>Playerid16</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.matchID %></td>
        <td><%= match.time %></td>
        <td><%= match.team %></td>
        <td><%= match.against %></td>
        <td><%= match.competition %></td>
        <td><%= match.scoreFor %></td>
        <td><%= match.scoreAgainst %></td>
        <td>
          <% match.players.each do |player| %>
            <%= player.name %>
          <% end %>
        </td>
        <td><%= match.playerID2 %></td>
        <td><%= match.playerID3 %></td>
        <td><%= match.playerID4 %></td>
        <td><%= match.playerID5 %></td>
        <td><%= match.playerID6 %></td>
        <td><%= match.playerID7 %></td>
        <td><%= match.playerID8 %></td>
        <td><%= match.playerID9 %></td>
        <td><%= match.playerID10 %></td>
        <td><%= match.playerID11 %></td>
        <td><%= match.playerID12 %></td>
        <td><%= match.playerID13 %></td>
        <td><%= match.playerID14 %></td>
        <td><%= match.playerID15 %></td>
        <td><%= match.playerID16 %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Matchid:</strong>
  <%= @match.matchID %>
</p>

<p>
  <strong>Time:</strong>
  <%= @match.time %>
</p>

<p>
  <strong>Team:</strong>
  <%= @match.team %>
</p>

<p>
  <strong>Against:</strong>
  <%= @match.against %>
</p>

<p>
  <strong>Competition:</strong>
  <%= @match.competition %>
</p>

<p>
  <strong>Scorefor:</strong>
  <%= @match.scoreFor %>
</p>

<p>
  <strong>Scoreagainst:</strong>
  <%= @match.scoreAgainst %>
</p>

<p>
  <strong>Playerid1:</strong>
  <%= @match.playerID1 %>
</p>

<p>
  <strong>Playerid2:</strong>
  <%= @match.playerID2 %>
</p>

<p>
  <strong>Playerid3:</strong>
  <%= @match.playerID3 %>
</p>

<p>
  <strong>Playerid4:</strong>
  <%= @match.playerID4 %>
</p>

<p>
  <strong>Playerid5:</strong>
  <%= @match.playerID5 %>
</p>

<p>
  <strong>Playerid6:</strong>
  <%= @match.playerID6 %>
</p>

<p>
  <strong>Playerid7:</strong>
  <%= @match.playerID7 %>
</p>

<p>
  <strong>Playerid8:</strong>
  <%= @match.playerID8 %>
</p>

<p>
  <strong>Playerid9:</strong>
  <%= @match.playerID9 %>
</p>

<p>
  <strong>Playerid10:</strong>
  <%= @match.playerID10 %>
</p>

<p>
  <strong>Playerid11:</strong>
  <%= @match.playerID11 %>
</p>

<p>
  <strong>Playerid12:</strong>
  <%= @match.playerID12 %>
</p>

<p>
  <strong>Playerid13:</strong>
  <%= @match.playerID13 %>
</p>

<p>
  <strong>Playerid14:</strong>
  <%= @match.playerID14 %>
</p>

<p>
  <strong>Playerid15:</strong>
  <%= @match.playerID15 %>
</p>

<p>
  <strong>Playerid16:</strong>
  <%= @match.playerID16 %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :playerID %><br>
    <%= f.number_field :playerID %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :team %><br>
    <%= f.number_field :team %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.number_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :availabilityNotes %><br>
    <%= f.text_field :availabilityNotes %>
  </div>
  <div class="field">
    <%= f.label :unavailableFrom %><br>
    <%= f.text_field :unavailableFrom %>
  </div>
  <div class="field">
    <%= f.label :unavailableUntil %><br>
    <%= f.text_field :unavailableUntil %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>
<h2>
  <a href="https://practice-database-simonina.c9users.io/matches">Matches</a>
</h2>
<h2>
  <a href="https://practice-database-simonina.c9users.io/captains">Captains</a>
</h2>

<table>
  <thead>
    <tr>
      <th>Playerid</th>
      <th>Name</th>
      <th>Team</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Availabilitynotes</th>
      <th>Unavailablefrom</th>
      <th>Unavailableuntil</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.playerID %></td>
        <td><%= player.name %></td>
        <td><%= player.team %></td>
        <td><%= player.email %></td>
        <td><%= player.mobile %></td>
        <td><%= player.availabilityNotes %></td>
        <td><%= player.unavailableFrom %></td>
        <td><%= player.unavailableUntil %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Playerid:</strong>
  <%= @player.playerID %>
</p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @player.team %>
</p>

<p>
  <strong>Email:</strong>
  <%= @player.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @player.mobile %>
</p>

<p>
  <strong>Availabilitynotes:</strong>
  <%= @player.availabilityNotes %>
</p>

<p>
  <strong>Unavailablefrom:</strong>
  <%= @player.unavailableFrom %>
</p>

<p>
  <strong>Unavailableuntil:</strong>
  <%= @player.unavailableUntil %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>